### ISSUE TITLE
DataMapper: missing elements inherited via complex type extension

### ISSUE THREAD

**Issue by lmajer999** [KaotoIO/kaoto#2505]
### **Please describe the feature that you want to propose**

1) In Kaoto DataMapper, I’m currently unable to select a specific element from an XSD schema (e.g., “SecondRequest” in the XSD below). It always selects the first element. 
My workaround is to copy the XSD for each mapper and move the desired element to the top, but that leads to multiple copies of the same file. It would be great to have a selector (e.g., a dropdown) to choose the specific element.

2) The data mapper doesn’t display elements added via type extension
(line 10 in sample xsd below: <xsd:extension base="msg:BaseRequest"> )

<img width="478" height="453" alt="Image" src="https://github.com/user-attachments/assets/ab16f078-fee6-42a0-9b18-5f90f2fa72b8" />

Would be great if all elements were displayed... 

Sample XSD Schema:

```
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.example.com/TEST"
    xmlns="http://www.example.com/TEST"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

    <xsd:element name="Request">
        <xsd:complexType>
            <xsd:complexContent>
                <xsd:extension base="BaseRequest">
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:extension>
            </xsd:complexContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="SecondRequest">
        <xsd:complexType>
            <xsd:complexContent>
                <xsd:extension base="BaseRequest">
                    <xsd:sequence>
                        <xsd:element name="user" type="xsd:string"/>
                        <xsd:element name="message" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:extension>
            </xsd:complexContent>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType abstract="true" name="BaseRequest">
        <xsd:complexContent>
            <xsd:extension base="Message">
                <xsd:sequence>
                    <xsd:element name="user" nillable="true" type="xsd:string">
                        <xsd:annotation>
                            <xsd:documentation>blah blah</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType abstract="true" name="Message">
        <xsd:sequence>
            <xsd:annotation>
                <xsd:documentation>Message body.
                </xsd:documentation>
            </xsd:annotation>
            <xsd:element minOccurs="0" name="timestamp" nillable="true" type="xsd:dateTime">
                <xsd:annotation>
                    <xsd:documentation>Timestamp when message was sent.
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>
```

**Comment by lordrip** [comment]
Hi @lmajer999, thanks for reporting it. If I'm not mistaken, this has been reported and fixed here https://github.com/KaotoIO/kaoto/issues/1814. If I understood you correctly, you want a selector to pick what the root element of the XSD schema is, is that right?

**Comment by lmajer999** [comment]
Hi @lordrip , thanks for fast response
Yes that's correct - for the fist point...
(Im sorry for creating similar/duplicate issue, I haven't seen this one, because default filter is set to show only open issues) 
Anyway issue is marked as completed with milestone 2.7.0 - I'm using VS Code with kaoto extension v2.7.0 and I still cant choose element from xsd schema, so will this feature be added in the next version?

+ the second point still applies - visual editor does not display elements referenced by extension (see screenshot - fields "user" and "timestamp" are missing)

**Comment by lhein** [comment]
2.7 hasn't been released yet. I am pretty sure you are on an older version if you haven't built your own snapshot.

**Comment by lmajer999** [comment]
I'm trying to stay up to date - I'm using vscode-kaoto-2.7.0-338 from [this link](https://download.jboss.org/jbosstools/vscode/snapshots/vscode-kaoto/)

So I guess this feature is not even in these snapshots yet... I will wait patiently for release, thank you.
Edit: after restarting VSCode with newest version, this feature appeared and works flawlessly, thank you !

**Comment by lhein** [comment]
Ah nice, thank you for the update. So I am surprised the feature is not included. We will check it on our side. Thanks for reporting it.

**Comment by igarashitm** [comment]
Hello @lmajer999 

I just tried vscode-kaoto-2.7.0-338 and I do see the dropdown to choose root element in the attache schema modal. Could you try to uninstall kaoto extension and install it again, then restart the vscode?

<img width="1408" height="1057" alt="Image" src="https://github.com/user-attachments/assets/9ce9663b-c058-4350-9fb6-97afc87b2c54" />

**Comment by lmajer999** [comment]
Yes, after restarting VSCode this feature appeared and works as expected, I already edited my last comment and closed the issue as duplicate...

**Comment by lhein** [comment]
Thanks for the confirmation!

**Comment by igarashitm** [comment]
Filed a separate issue for the 2nd point - https://github.com/KaotoIO/kaoto/issues/2514
