### ISSUE TITLE
Nodes/container ordering issue in doTry EIP

### ISSUE THREAD

**Issue by shivamG640** [KaotoIO/kaoto#2796]
### Describe the Bug

In DoTry container, the order of the nodes/container changes when adding a new step.

### Steps to Reproduce the Bug or Issue

1. Create a route and a DoTry EIP.
2. Try adding step to the DoTry EIP and notice how the ordering changes.

### Screenshots or Videos

https://github.com/user-attachments/assets/2c2c076c-50f6-4901-9553-8311e2757e8a

### Platform

- OS: Linux
- Browser: Chrome

**Comment by lhein** [comment]
@lordrip is that fixed by the work you are doing around sorting the parameters by index in catalog?

**Comment by lordrip** [comment]
@lhein, I'm not sure, we need to try again once both PRs are merged:

* https://github.com/KaotoIO/kaoto/pull/2854
* https://github.com/KaotoIO/kaoto/pull/2874

**Comment by shivamG640** [comment]
Not reproducible on Kaoto online, so this issue is considered resolved. Hence marking it as closed.

**Comment by shivamG640** [comment]
Found that this is still not resolved.

https://github.com/user-attachments/assets/0fdaa890-06f8-48ff-9679-52e74bd22ac3

**Comment by shivamG640** [comment]
Please check this Slack thread for a proposed solution to address this and all similar problems: https://ibm-cloud.slack.com/archives/C09257QGCAD/p1773932186951629?thread_ts=1773926341.231739&cid=C09257QGCAD
